import jsPDF from "jspdf";

export function generatePDF(feedback: string[]): void {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = margin;

  // Header background bar
  doc.setFillColor(15, 23, 42); // dark navy
  doc.rect(0, 0, pageWidth, 45, "F");

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text("CRICKET POSTURE ANALYSIS REPORT", pageWidth / 2, 20, {
    align: "center",
  });

  doc.setFontSize(10);
  doc.setTextColor(148, 163, 184);
  doc.text("Posture Based Technique Feedback System", pageWidth / 2, 30, {
    align: "center",
  });

  // Accent bar
  doc.setFillColor(59, 130, 246);
  doc.rect(0, 43, pageWidth, 2, "F");

  y = 60;

  // Date and Shot Type
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  doc.text("Report Generated:", margin, y);
  doc.setTextColor(30, 41, 59);
  doc.text(new Date().toLocaleString(), margin + 38, y);
  y += 8;

  doc.setTextColor(71, 85, 105);
  doc.text("Shot Type:", margin, y);
  doc.setTextColor(30, 41, 59);
  doc.text("Cover Drive", margin + 28, y);
  y += 15;

  // Section heading
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(15, 23, 42);
  doc.text("BIOMETRIC ANALYSIS", margin, y);

  // Underline
  doc.setDrawColor(59, 130, 246);
  doc.setLineWidth(0.8);
  doc.line(margin, y + 2, margin + 55, y + 2);
  y += 12;

  // Feedback items
  feedback.forEach((item, index) => {
    if (y > 260) {
      doc.addPage();
      y = 20;
    }

    // Card background
    doc.setFillColor(239, 246, 255);
    doc.roundedRect(margin, y - 4, pageWidth - margin * 2, 12, 2, 2, "F");

    // Blue left accent
    doc.setFillColor(59, 130, 246);
    doc.rect(margin, y - 4, 3, 12, "F");

    // Index badge
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(59, 130, 246);
    doc.text(`${index + 1}.`, margin + 6, y + 3);

    // Item text
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);
    doc.text(item, margin + 14, y + 3);

    y += 15;
  });

  y += 10;

  // Footer
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text(
    "Generated by Cricket Posture Detection System • caffeine.ai",
    pageWidth / 2,
    y,
    { align: "center" },
  );

  doc.save(`cricket-posture-report-${Date.now()}.pdf`);
}
